name: Deploy to Pypi

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Get GH tag 
        run: |
          echo "Tag name from github.ref_name: ${{ github.ref_name }}"
